repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        args: ["--py36-plus"]
        language: system
        types: [python]

      - id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        require_serial: true
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        args: [--show-error-codes]
        language: system
        require_serial: true
        types: [python]

      - id: blacken-docs
        name: blacken-docs
        entry: blacken-docs
        language: system
        require_serial: true
        files: '\.(rst|md|markdown|py|tex)$'
